### ISSUE TITLE
[8.0 R530] File>Update crashes

### ISSUE THREAD

**Issue by Yani-ABDESSELAM** [ho-dev/HattrickOrganizer#1941]
File>Update crashes

**Additional information**

File>Update crashes
V8.0 DEV (r530)

**java.lang.NullPointerException: Cannot invoke "Object.toString()" because "preparedStatement" is null**

_java.lang.NullPointerException: Cannot invoke "Object.toString()" because "preparedStatement" is null
	at core.db.JDBCAdapter.executePreparedUpdate(JDBCAdapter.java:134)
	at core.db.AbstractTable.executePreparedInsert(AbstractTable.java:370)
	at core.db.AbstractTable.insert(AbstractTable.java:111)
	at core.db.AbstractTable.store(AbstractTable.java:99)
	at core.db.MatchesKurzInfoTable.storeMatchKurzInfos(MatchesKurzInfoTable.java:84)
	at core.db.DBManager.storeMatchKurzInfos(DBManager.java:1177)
	at core.net.OnlineWorker.getMatches(OnlineWorker.java:531)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:322)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)_

**Comment by tychobrailleur** [comment]
This should now be addressed in recent commits.

**Comment by Yani-ABDESSELAM** [comment]
I just tested with R575 and got another issue :

java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: MATCHTYP in statement [SELECT * FROM MATCHDETAILS  WHERE MatchID = ? AND MatchTyp = ?]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at core.db.StatementCache.createStatement(StatementCache.kt:52)
	at core.db.StatementCache.getPreparedStatement(StatementCache.kt:71)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:61)
	at core.db.AbstractTable.executePreparedSelect(AbstractTable.java:421)
	at core.db.AbstractTable.loadOne(AbstractTable.java:141)
	at core.db.MatchDetailsTable.loadMatchDetails(MatchDetailsTable.java:102)
	at core.db.DBManager.loadMatchDetails(DBManager.java:1420)
	at core.model.match.Matchdetails.getMatchdetails(Matchdetails.java:232)
	at core.model.match.MatchKurzInfo.getMatchdetails(MatchKurzInfo.java:469)
	at core.model.match.MatchKurzInfo.getDuration(MatchKurzInfo.java:450)
	at core.db.MatchesKurzInfoTable.lambda$initColumns$42(MatchesKurzInfoTable.java:57)
	at core.db.AbstractTable.lambda$insert$0(AbstractTable.java:111)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at core.db.AbstractTable.insert(AbstractTable.java:112)
	at core.db.AbstractTable.store(AbstractTable.java:98)
	at core.db.MatchesKurzInfoTable.storeMatchKurzInfos(MatchesKurzInfoTable.java:83)
	at core.db.DBManager.storeMatchKurzInfos(DBManager.java:1141)
	at core.net.OnlineWorker.getMatches(OnlineWorker.java:529)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:322)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: MATCHTYP
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 65 more

**Comment by tychobrailleur** [comment]
Odd, `MATCHTYP` is a column that seems to have been there since HO v5.0.0, are you upgrading HO from an early version?

**Comment by Yani-ABDESSELAM** [comment]
> Odd, `MATCHTYP` is a column that seems to have been there since HO v5.0.0, are you upgrading HO from an early version?

Yes, but I used latest exe with bundled JRE and there's no trace of previous version in the folder.
You mean in the database ?
I had this error when I try to import previous database up to version R576

Now with R577 it crashes at application start :
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at core.HO.main(HO.java:115)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by Yani-ABDESSELAM** [comment]
With R8.0.578.0 It still crashes at start when I try to download update :

java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: MATCHTYP in statement [SELECT * FROM MATCHDETAILS  WHERE MatchID = ? AND MatchTyp = ?]
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at core.db.StatementCache.createStatement(StatementCache.kt:52)
	at core.db.StatementCache.getPreparedStatement(StatementCache.kt:71)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:61)
	at core.db.AbstractTable.executePreparedSelect(AbstractTable.java:421)
	at core.db.AbstractTable.loadOne(AbstractTable.java:141)
	at core.db.MatchDetailsTable.loadMatchDetails(MatchDetailsTable.java:102)
	at core.db.DBManager.loadMatchDetails(DBManager.java:1420)
	at core.model.match.Matchdetails.getMatchdetails(Matchdetails.java:232)
	at core.model.match.MatchKurzInfo.getMatchdetails(MatchKurzInfo.java:469)
	at core.model.match.MatchKurzInfo.getDuration(MatchKurzInfo.java:450)
	at core.db.MatchesKurzInfoTable.lambda$initColumns$42(MatchesKurzInfoTable.java:57)
	at core.db.AbstractTable.lambda$insert$0(AbstractTable.java:111)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at core.db.AbstractTable.insert(AbstractTable.java:112)
	at core.db.AbstractTable.store(AbstractTable.java:98)
	at core.db.MatchesKurzInfoTable.storeMatchKurzInfos(MatchesKurzInfoTable.java:83)
	at core.db.DBManager.storeMatchKurzInfos(DBManager.java:1141)
	at core.net.OnlineWorker.getMatches(OnlineWorker.java:529)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:322)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: MATCHTYP
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.QueryExpression.resolve(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 65 more

**Comment by Yani-ABDESSELAM** [comment]
Same issue with R581

**Comment by wsbrenk** [comment]
@Yani-ABDESSELAM could you upload your database to this threat? Please search in the folder %APPDATA%/HO/db the backups of your database (zip-file).

**Comment by Yani-ABDESSELAM** [comment]
> @Yani-ABDESSELAM could you upload your database to this threat? Please search in the folder %APPDATA%/HO/db the backups of your database (zip-file).

Yes, of course.
Sorry for late reply, you can find my DB here :

[db_user-2024-01-27.zip](https://github.com/ho-dev/HattrickOrganizer/files/14070368/db_user-2024-01-27.zip)

**Comment by wsbrenk** [comment]
Parts of updateDBv500 were not executed.

**Comment by Yani-ABDESSELAM** [comment]
> Parts of updateDBv500 were not executed.

Ok, do you know how to ensure updateDBv500 is fully executed ?
If you need any help or any additional information, please let me know ;)

**Comment by wsbrenk** [comment]
~~~
	case 701:
		// user database found with corrupt v5 upgrade (see https://github.com/ho-dev/HattrickOrganizer/issues/1941)
		updateDBv500(DBVersion);
		updateDBv800(DBVersion);
	case 800:
~~~

running v500 update and downloading (F11) will fix this issue:

![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/2152faf3-cbea-4bc8-be4f-bdc1115ad803)

**Comment by wsbrenk** [comment]
@Yani-ABDESSELAM I suspect this can only have happened to users who had worked with a V5 development version.

**Comment by Yani-ABDESSELAM** [comment]
> @Yani-ABDESSELAM I suspect this can only have happened to users who had worked with a V5 development version.

Yes, it's more than likely, I've tested all kinds of development builds.

**Comment by Yani-ABDESSELAM** [comment]
@wsbrenk : Works for me with R586 (8.0.586.0).
Thanks a lot !!!!
